### ISSUE TITLE
question: seo

### ISSUE THREAD

**Issue by marcobiedermann** [oyvindrobertsen/awesome-awesome#6]
I've created a list of helpful search engine optimization tipps and tricks.
Are you interested in adding it? I can send you a PR if you like to.

If so, how should the category be named?

https://github.com/marcobiedermann/search-engine-optimization

**Comment by oyvindrobertsen** [comment]
Sure! The category could just be SEO.

**Comment by marcobiedermann** [comment]
Alright, will add it later. :)
