### ISSUE TITLE
Suggestion: merge with sindresorhus/awesome

### ISSUE THREAD

**Issue by waldyrious** [oyvindrobertsen/awesome-awesome#9]
It would be nice to merge efforts.
Clickable link: https://github.com/sindresorhus/awesome
/cc @sindresorhus

**Comment by oyvindrobertsen** [comment]
I don't think my repo has anything that @sindresohus' repo doesn't already have.

**Comment by waldyrious** [comment]
@oyvindrobertsen if that's the case, would you consider changing the README to a link to that repo, then? And if not, why not?

**Comment by oyvindrobertsen** [comment]
Good idea! No objections :smile:

**Comment by waldyrious** [comment]
Oh, sorry, I must have not been clear. I meant actually replacing the README contents with a link to that repo (I'm seeking to get those two merged, see https://github.com/sindresorhus/awesome/issues/157). But of course, I understand if you prefer to keep your repo separately as well.
